Sssilviaa/readme
CMU-Robotics-Club/RoboBuggy2 pull request #20
Opened 2023-09-21 23:26 UTC by SSSilviaa

2023-09-21 23:38 UTC, christianvluu commented
Can you also edit "Installation" section to include the steps you followed last time?

2023-09-22 00:00 UTC, SSSilviaa commented
> Can you also edit "Installation" section to include the steps you followed last time?

Oops. I am very sorry. If you are referring to the set up steps you so kindly helped me do last time, I barely remember all the complicated steps. But would happily edit it if we could talk it over next meeting.

2023-09-22 00:13 UTC, christianvluu commented
> > Can you also edit "Installation" section to include the steps you followed last time?
> 
> Oops. I am very sorry. If you are referring to the set up steps you so kindly helped me do last time, I barely remember all the complicated steps. But would happily edit it if we could talk it over next meeting.

Let's talk over it next meeting. Please remind me about this.

2023-09-22 00:13 UTC, christianvluu commented
@Jackack for visibility

2023-09-22 00:25 UTC, Jackack commented on README.md
Not everyone's Robobuggy directory will be located in the same place on their machine, so the cd instructions won't work for everyone. We should just leave it to the reader to navigate to their Robobuggy folder. Also, why do we need to open file explorer?

2023-09-30 02:47 UTC, christianvluu commented
Can you also remove the section on the 3D simulator. That is deprecated.

2023-09-30 02:48 UTC, christianvluu commented
I think there's a way to insert those youtube videos I made into the readme directly without linking it to YouTube - that might be helpful.

2023-09-30 02:48 UTC, christianvluu commented
@Jackack visibility.

2023-09-30 22:05 UTC, SSSilviaa commented
> Can you also remove the section on the 3D simulator. That is deprecated.

removed now

2023-09-30 22:06 UTC, SSSilviaa commented
> I think there's a way to insert those youtube videos I made into the readme directly without linking it to YouTube - that might be helpful.

I succeeded by half. The video can play by clicking on the image now. However, then the video fills the whole screen and cannot become small again.

2023-10-03 03:51 UTC, christianvluu commented
Not sure if you're not seeing it but there's a few comments left I made above that are unresolved.

2023-10-03 11:40 UTC, SSSilviaa commented
> Not sure if you're not seeing it but there's a few comments left I made above that are unresolved.

Which ones? I don’t think I see them

2023-10-03 16:07 UTC, christianvluu requested changes
Please See comments

2023-10-06 22:58 UTC, SSSilviaa commented on README.md
> +- Open Foxglove, choose the third one to start link.
Can you replace my screenshot of the start link with your english version? Somehow I cannot change the language. And where can I find the URL to connect?

2023-10-09 02:51 UTC, christianvluu commented
Thanks for the edits. But for next time, please don't resolve these messages on your own - the idea is the reviewer who looks at them initially resolves them.

2023-10-09 02:54 UTC, christianvluu commented on README.md
> +- Open Foxglove, choose the third one to start link.
Your screen shot is fine, URL ws://localhost:8765

2023-10-09 02:59 UTC, christianvluu commented on README.md
> +- Open Foxglove, choose the third one to start link.
Actually, this is fine. I wouldn't worry about it :)

2023-10-09 03:00 UTC, christianvluu approved these changes
Thank you for the changes! Good work! :) We'll get you up to speed on the next task soon.

@Jackack for visibility

2023-10-09 03:03 UTC, merged