Jackack/nand sim
CMU-Robotics-Club/RoboBuggy2 pull request #26
Opened 2023-10-23 17:55 UTC by Jackack

Added ability to simulate multiple buggies. Due to topic name collision during sim, append buggy name to topics. Changed main and sim launch files to pass buggy name and is_sim into auto nodes. 

Tested simulation with two buggies inside wsl+docker. Todo: test updated sim code on short circuit.

2023-10-23 18:18 UTC, christianvluu commented
Can you update documentation on how to use this sim too? (e.g. how to launch, interact, interface, etc.)

2023-10-23 18:23 UTC, christianvluu requested changes
And can you add screenshots? And also make a note in the documentation or in the git commit message when you merge that this does not contain the X11 visualization edits.

2023-10-23 18:23 UTC, christianvluu commented on rb_ws/src/buggy/scripts/2d_sim/engine.py
> +    def __init__(self, starting_pose, velocity, buggy_name):
typing

2023-10-23 18:23 UTC, christianvluu commented on rb_ws/src/buggy/scripts/2d_sim/engine.py
>              heading (float): degrees start heading of buggy
functions headers

2023-11-13 21:01 UTC, Jackack commented
Added all requested changes

2023-11-13 21:03 UTC, christianvluu approved these changes

2023-11-13 22:40 UTC, merged